### ISSUE TITLE
Not compatiable with my VS code

### ISSUE THREAD

**Issue by ruisonghan** [schrej/vscode-omnetpp-ned#1]
Hi, 

May I know when will you update the package again? It is not compatible with my current VS
Code （under Linux) . Thanks!
```bash
Unable to install because, the extension 'schrej.omnetpp-ned' compatible with current version '1.32.3' of VS Code is not found.
```

**Comment by schrej** [comment]
The extension required VS Code 1.33.0 or higher, probably set automatically while initialising the extension project. I've reduced it to 1.0.0 now, so it should work with your (outdated 😄) version now!

**Comment by ruisonghan** [comment]
Thanks so much.
