### ISSUE TITLE
Incorrect hightlight in the Ned file.

### ISSUE THREAD

**Issue by ruisonghan** [schrej/vscode-omnetpp-ned#2]
Hi,

It is me again. When meeting the following condition, your package will highlight the "5" in ItsG5Service, and I think you could update the rules of analyzing the proper nouns in the Ned file. Thanks a lot.
```
simple CaService like ItsG5Service
{
    parameters:
                        ...
}
```

**Comment by schrej** [comment]
Yeah, I just noticed that as well. Probably needs some tuning of the numeric regex.
